### ISSUE TITLE
support for Dart 2.1

### ISSUE THREAD

**Issue by mathieujobin** [kumar8600/dart-oauth1#4]
```
/home/mathieu/projects/mobile-development/flutter/bin/flutter --no-color packages upgrade
Running "flutter packages upgrade" in multilearning...
The current Dart SDK version is 2.1.0-dev.4.0.flutter-4eb879133a.

Because multilearning depends on oauth1 from git which requires SDK version <2.0.0, version solving failed.
pub upgrade failed (1)
Process finished with exit code 1
```

I could try just bumping the lock, but I'm not sure what issues might arise.
do you plan on supporting Dart 2.1 ?

**Comment by mathieujobin** [comment]
the error message is misleading, the requirement is not from `oauth1` like it says, but my app.
will reopen if this is really a problem but look like it is not

**Comment by mathieujobin** [comment]
issue is caused by `unittest`

```
cat hosted/pub.dartlang.org/unittest-0.11.7/pubspec.yaml 
name: unittest
version: 0.11.7
author: Dart Team <misc@dartlang.org>
description: A library for writing dart unit tests.
homepage: https://github.com/dart-lang/old_unittest
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  stack_trace: '>=0.9.0 <2.0.0'
dev_dependencies:
  metatest: '>=0.1.0 <0.2.0'
```
